"use client";

import { FileText } from "lucide-react";

const KPI_ITEMS = [
  { label: "NPS SCORE",  value: "72"   },
  { label: "CHURN RATE", value: "2.4%" },
  { label: "AVG RATING", value: "4.8"  },
  { label: "RESPONSE",   value: "1.2h" },
];

const RECOMMENDATIONS = [
  "Prioritize mobile checkout flow optimization based on 15% drop-off rate identified in customer feedback.",
  "Scale automated customer support for level 1 inquiries to maintain < 2h response time.",
  "Introduce loyalty program for high-tier enterprise clients to reduce churn risk in Q4.",
];

export function PDFPreview() {
  return (
    <div className="bg-[#1E293B] border border-[#334155] rounded-xl p-5">
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        <div className="p-1.5 rounded-lg bg-blue-500/20">
          <FileText size={14} className="text-blue-400" />
        </div>
        <h3 className="text-sm font-semibold text-[#F8FAFC]">PDF Preview</h3>
      </div>

      {/* PDF mock document */}
      <div className="bg-[#0F172A] border border-[#334155] rounded-xl p-6 min-h-[520px] flex flex-col gap-6">
        {/* Document header */}
        <div className="flex items-start justify-between">
          <div>
            <p className="text-[10px] font-bold text-purple-400 uppercase tracking-widest mb-1">
              Executive Summary
            </p>
            <h2 className="text-xl font-bold text-[#F8FAFC]">
              ReviewSense_Q3_2023.pdf
            </h2>
          </div>
          <span className="px-3 py-1 rounded-lg bg-purple-500/20 text-purple-400 text-[10px] font-bold border border-purple-500/30 uppercase tracking-wider">
            Confidential
          </span>
        </div>

        {/* KPI grid */}
        <div className="grid grid-cols-4 gap-3">
          {KPI_ITEMS.map(({ label, value }) => (
            <div
              key={label}
              className="bg-[#1E293B]/60 border border-[#334155] rounded-lg p-3"
            >
              <p className="text-[9px] font-bold text-[#94A3B8] uppercase tracking-wider mb-1">
                {label}
              </p>
              <p className="text-xl font-black text-[#F8FAFC]">{value}</p>
            </div>
          ))}
        </div>

        {/* Recommendations */}
        <div>
          <h4 className="text-sm font-bold text-[#F8FAFC] mb-3">
            Strategic Recommendations
          </h4>
          <ul className="flex flex-col gap-3">
            {RECOMMENDATIONS.map((rec, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-[#94A3B8] leading-relaxed">
                <div className="w-1.5 h-1.5 rounded-full bg-[#94A3B8] mt-1.5 shrink-0" />
                {rec}
              </li>
            ))}
          </ul>
        </div>

        {/* Footer */}
        <div className="mt-auto pt-4 border-t border-[#334155] flex items-center justify-between">
          <p className="text-[10px] text-[#475569] italic">
            Generated by ReviewSense AI Engine on Oct 12, 2023
          </p>
          <div className="flex gap-1">
            {[1, 2, 3].map((i) => (
              <div key={i} className="w-1.5 h-1.5 rounded-full bg-[#334155]" />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}